<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-APPR_PART_1_POE-4a4d9890-62fa-4fd8-a13d-7ad6c1a58a6a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GiftOfTheGivers.Common" Version="1.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.20" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.20" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.20" />
    <PackageReference Include="xunit.abstractions" Version="2.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\images\" />
  </ItemGroup>

	<ItemGroup>
		<Compile Remove="GiftoftheGivers.Functions\**" />
		<Content Remove="GiftoftheGivers.Functions\**" />
		<None Remove="GiftoftheGivers.Functions\**" />
	</ItemGroup>
</Project>
